---
version: '2'

tasks:
  fix-cs:
    desc: "Fix code style"
    cmds:
      - docker run --rm -iv $PWD:/data/ cytopia/php-cs-fixer fix

  lint:
    desc: "Quick tests not required to build app"
    cmds:
      - task: lint-mnd
      - task: lint-cs
  lint-cs:
    desc: "Validate code style"
    cmds:
      - docker run --rm -iv $PWD:/data/ cytopia/php-cs-fixer fix --dry-run --diff
  lint-mnd:
    desc: "Validate no magic numbers"
    cmds:
      - docker run --rm -v $PWD:/app dockerizedphp/phpmnd /app
        --exclude=var --exclude=vendor --exclude=src/Pcs/Resources/blockslib/blocks
        --non-zero-exit-on-violation
  lint-phpstan:
    desc: "Validate phpstan"
    cmds:
      - docker run --rm -v $PWD:/app phpstan/phpstan analyse /app
