name: onpush
on: [push]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Pre-build validations
        run: make lint
      - name: Build
        run: make build
      - name: Test
        run: make test
