name: onpush
on: [push]
jobs:
  integration-pipeline:
    name: Integration pipeline
    runs-on: ubuntu-latest
    on: # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#push
      push
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Pre-build validations
        run: make lint
      - name: Build
        run: make build
      - name: Test
        run: make test
