name: onpush
on: [push] # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#push
jobs:
  test:
    name: Integration pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pre-build validations
        run: make lint
      - name: Build
        run: make build
      - name: Test
        run: make test
  release:
    name: Release app
    if: startsWith(github.ref, 'refs/tags/')
    needs:
      - test
    strategy:
      matrix:
        include:
          - goos: linux
            os: ubuntu-22.04
          - goos: darwin
            os: macos-12
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build binary files
        run: make BINARY_PATH="release/syml" CGO_ENABLED=0 GOOS=${{ matrix.goos }} GOARCH=amd64 compile;
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: release/syml-${{ matrix.goos }}
          draft: true
